# Generated by Django 3.0.3 on 2020-08-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
    ]
