# Generated by Django 3.0.3 on 2020-08-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200821_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
