# Generated by Django 3.0.3 on 2020-08-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200825_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
    ]
