# Generated by Django 3.0.3 on 2020-08-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='c_name',
            new_name='category',
        ),
    ]
