# Generated by Django 3.0.3 on 2020-08-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200825_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
