# Generated by Django 3.0.3 on 2020-08-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='nearestloc',
        ),
        migrations.DeleteModel(
            name='nearestloc',
        ),
    ]
