# Generated by Django 3.0.3 on 2020-08-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200826_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
