# Generated by Django 3.0.3 on 2020-08-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
