# Generated by Django 3.0.3 on 2020-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200823_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
