# Generated by Django 3.0.3 on 2020-08-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.CharField(max_length=10),
        ),
    ]
