# Generated by Django 3.0.3 on 2020-08-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200823_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
